# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'bloo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for bloo
  pod 'Firebase/Auth'
  pod 'Firebase/Crash'
  pod 'Firebase/Database'
  pod 'Firebase/Messaging'
  pod 'Firebase/Storage'
  pod 'GoogleSignIn'
  pod 'GeoFire', :git => 'https://github.com/firebase/geofire-objc.git'
  
  target 'blooTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'blooUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
